"""
AFRC
An analytical version of the Flory Random Coil for polypeptides, implemented using the rotational isomeric state
approximation of Flory and Volkenstein and parameterized on the excluded volume dihedral backbone maps.

Copyright Alex Holehouse 2018-2026 (holehouselab.com).

For any questions please contact Alex.

"""

# Add imports here
from afrc.afrc import *  # noqa: F401,F403


def _resolve_version():
    """
    Resolve the package version, trying three sources in turn.

    """

    # _version.py is generated by versioningit at build/install time and is the
    # authoritative source for an installed package. Note that in a git checkout
    # the file holds whatever the last build wrote, so it can lag the repository
    # until the next build/install.
    try:
        from ._version import __version__ as generated_version
        return generated_version
    except Exception:
        # missing (never built) or unreadable (e.g. an interrupted build left a
        # truncated file behind) - fall through to the alternatives rather than
        # making the whole package unimportable
        pass

    # an installed package that lacks the generated file - the package metadata
    # still records the installed version
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as metadata_version
    try:
        return metadata_version('afrc')
    except PackageNotFoundError:
        pass

    # a raw, uninstalled source checkout (e.g. a Read the Docs build) - compute
    # the version from the repository itself, anchored to this file rather than
    # the working directory. Deliberately not wrapped in a silent except: if this
    # fails as well (versioningit absent, not a git repository) the import should
    # fail loudly so the misconfiguration is caught, rather than shipping a
    # placeholder version.
    import os
    import versioningit
    return versioningit.get_version(os.path.join(os.path.dirname(__file__), os.pardir))


__version__ = _resolve_version()
